name: build-pdf-all-weeks

on: workflow_dispatch

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          pip install -r requirements.txt
          sudo apt-get install pandoc
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
      - name: Compile
        run: |
          python compile_all_cw.py pdf
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: weekly-report
          path: |
            build
          retention-days: 3
