name: build-md-all-weeks

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          pip install -r requirements.txt
      - name: Compile
        run: |
          python compile_all_cw.py
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: weekly-report
          path: |
            build
          retention-days: 3
